
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import AppProvider from '../../providers/AppProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bright Stars Education',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-gray-100'>
      <body className={inter.className}>
       <AppProvider>
      <Navbar/>
      {children}
        <Footer/>
       
        </AppProvider> 
        </body>
       
    </html>
  )
}
